error=Parameters of the abnormal
start_task=Start executing subtasks
pre_condition_failure=The preconditions of sub-task are not satisfied, and the main task number is:
pre_condition_failure_2=, condition handler:
pre_condition_success=All preconditions for sub-tasks have been met. Main task number:
pre_condition_success_2=, Shelves:
pre_condition_success_3=, the origin code:
pre_condition_success_4=, the end code:
create_task=Task creation completed, main task number:
post_condition_success=All post-conditions of sub-tasks have been met. Main task no. :
post_condition_failure=Sub-task postcondition is not satisfied, main task no. :
post_condition_failure_2=, condition name
send_success=Subtask sending completed, main task no. :
send_success_2=, the message body sent is:
callback_start=Subtask callback: subtask has begun
callback_leave=Subtask callback: the subtask has left the storage
callback_end=Subtask callback: subtask has ended
send_failure=Failed to issue sub-task, main task no. :
send_failure_2=, error message:


















